%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\^\Documents\MATLAB\Examples\R2023b\matlab\DeclareFunctionWithOneOutputExample\ed-p04.txt
%
% Auto-generated by MATLAB on 04-May-2024 23:00:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "error";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"], "FillValue", 0);

% Import the data
edp04 = readtable("ed-p04.txt", opts);

%% Convert to output type
edp04 = table2array(edp04);

%% Clear temporary variables
clear opts